### ISSUE TITLE
Implement PlaneType with an Enum

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/poppy#101]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josePhoenix](https://github.com/josePhoenix)**
_Tuesday Aug 11, 2015 at 02:39 GMT_
_Originally opened as https://github.com/mperrin/poppy/pull/101_

----

Introduces a dependency on the Python 3.4+ `enum` module, but the `enum34` backport is there as a dependency for older versions.

----

_**[josePhoenix](https://github.com/josePhoenix)** included the following code: https://github.com/mperrin/poppy/pull/101/commits_

**Comment by cslocum** [comment]
Sorry Marshall, I just saw this.  That's no problem.
