### ISSUE TITLE
Re-assign BUNIT hdr keyword sooner

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/poppy#285]
When an OPD file is loaded into a `FITSOpticalElement`, it is quite immediately re-scaled to be in units of meters (`poppy_core.py`, lines 2381-2387). However, the `BUNIT` header keyword corresponding to the OPD is not re-written to reflect this. This confused me, as I was looking at OPD arrays and seeing perturbations on the scale of meters, while the `opd_header` was still telling me the units were in microns.

The `BUNIT` keyword is eventually re-written if the OPD is written to an HDUList object in `webbpsf.opds.as_fits()`, but this isn't helpful for someone looking at the OPD array and header objects.

I think it would be wise to re-write this keyword to reflect that the OPD is now in units of meters as soon as the OPD is re-scaled. If there are no disagreements, I would be happy to submit a quick PR for it.

**Comment by mperrin** [comment]
That makes sense, sure. Thanks!
