### ISSUE TITLE
Notebook examples use deprecated function names

### ISSUE THREAD

**Issue by corcoted** [spacetelescope/poppy#287]
Some of the example notebooks no longer run since the name changes in version 0.8.0 because they use deprecated function names (e.g. calcPSF).

Should just need to rename.

**Comment by corcoted** [comment]
Submitted pull request #288

**Comment by corcoted** [comment]
It also looks like some of the tests still use the old function names, but I haven't been able to run them to check (config problem on my end).

**Comment by mperrin** [comment]
I found and fixed some instances of `_getOpticalSystem` in one of the test files, but that's all I can find in the tests. Are there other instances of any old function names that I'm missing?

**Comment by mperrin** [comment]
Fixed by #288
