### ISSUE TITLE
BUNIT of 'radian' for FITSOpticalElement

### ISSUE THREAD

**Issue by joseph-long** [spacetelescope/poppy#305]
While implementing our fancy vector apodizing phase plate in a POPPY model, I realized there's no obvious way to define a FITSOpticalElement in terms of phase alone. Because vAPPs  use "vector phase", the phase map is actually defined in radians / waves independent of wavelength.

If there's interest, I'd like to add support for phase maps in radians for FITSOpticalElements. Of course, I could just subclass it myself, but in the spirit of open-source I thought I'd see if you wanted this upstream 😄

**Comment by mperrin** [comment]
Yeah, sure, sounds useful. -- And you've surely earned the right to just submit any PR you want into this without having to ask first! :-)
