### ISSUE TITLE
Potential bug in poppy.measure_fwhm

### ISSUE THREAD

**Issue by kjbrooks** [spacetelescope/poppy#363]
In attempting to use poppy.utils.measure_fwhm, I ran into a TypeError: No loop matching the specified signature and casting was found for ufunc true_divide. 

It seems that this line: 

https://github.com/spacetelescope/poppy/blob/2010aaac2e738ac347186e28b2258e489a22deec/poppy/utils.py#L821

is causing an error since this operation is not actually valid for the reasons laid out in this issue: https://github.com/numpy/numpy/issues/10565/

It seems like a relatively simple solution of change that line to: `image = image / image.max()`

**Comment by mperrin** [comment]
Oh interesting. This is for an image with integer dtype? I think it sounds like  the existing code works for float but not for int? Good catch!

**Comment by kjbrooks** [comment]
Yes, this was an image that came out of MAGIC and is dtype uint16
