### ISSUE TITLE
documentation update? custom optic

### ISSUE THREAD

**Issue by Teusia** [spacetelescope/poppy#461]
Dear all,

I was trying to use the example [custom optic class](https://poppy-optics.readthedocs.io/en/latest/extending.html#defining-a-custom-optic-from-an-analytic-function) to make a wrapper, and I think the example might need up dating. 

First in the __init__ python complained that:
```python
  File "~/phaseContrastSensor.py", line 356, in <module>
    gmtp = GMTpoppy(nPx)

  File "~/phaseContrastSensor.py", line 20, in __init__
    poppy.AnalyticOpticalElement.__init__(**kwargs)

TypeError: __init__() missing 1 required positional argument: 'self'
```
(the GMTpoppy class was a pure copy paste of the example on [the page](https://poppy-optics.readthedocs.io/en/latest/extending.html#defining-a-custom-optic-from-an-analytic-function))
Adding the self in :
```python
poppy.AnalyticOpticalElement.__init__(self,**kwargs)
```
Does fix this error. Unless the problem is really elsewhere, maybe consider adding this `self` in the example?

Second (and this one is 'joke's on me' type) my custom optic is the first element of the optical system. This is obvious but Poppy complained that : 
```python
raise RuntimeError("You must define an entrance pupil diameter either on the OpticalSystem or its first optic.")
```
It took a bit of research but I figured that the other classes define the pupil diameter through an attribute `pupil_diam` and that assigning a value to this attribute solves this particular complaint.
There might be another page that tells what is the minimal requirements for the first optical element( which I did not find), in which case I think it might be interesting to link to that page. If not, I think it is worth adding in the example or one of the notes that special case when the custom optics is the first optics then there should be at least a `pupil_diam` attribute defined and initialised to a value. 

Otherwise bonus question since I am at it: are there other good practice things to do? Like enforcing a name on the optical element? Or maybe defining a plane type to make sure that `OpticalSystem` complains when you are trying to put in a pupil plane something that should be in an image plan? Let me know if you have time, I am curious.

In the hope this is useful input.
Best regards,
Anne-laure Cheffot

P.S.: suggested changes to the example : 
```python
class myCustomOptic(poppy.AnalyticOpticalElement):
    def __init__(self, *args, **kwargs):
        """ If your optic has adjustable parameters, then save them as attributes here 
        If your custom optics is your first optical surface assign a positive float to self.pupil_diam.
        e.g.: consider changing __init__ method to : 
            def __init__(self,pupil_diam, *args, **kwargs):
                self.pupil_diam = pupil_diam #before or after poppy.AnalyticOpticalElement makes no difference.
                poppy.AnalyticOpticalElement.__init__(self, **kwargs)
                #rest of your code
        """
        poppy.AnalyticOpticalElement.__init__(self, **kwargs)

    def get_opd(self,wave):
        y, x = self.get_coordinates(wave)
        opd = some_function(x,y, wave.wavelength, self)
        return opd

    def get_transmission(self, wave):
        y, x = self.get_coordinates(wave)
        transmission = other_function(x,y, wave.wavelength, self)
        return transmission

    # behind the scenes Poppy  will calculate:
    #    phasor = transmission = np.exp(1.j * 2 * np.pi / wave.wavelength * opd)
```

**Comment by mperrin** [comment]
Fixed as part of PR #449
