### ISSUE TITLE
Error with Astropy quantity comparison in `CompoundAnalyticOptic`

### ISSUE THREAD

**Issue by vandalt** [spacetelescope/poppy#485]
When running the code below to create a for a `CompoundAnalyticOptic` object in the [POPPY quickstart notebook](https://nbviewer.org/github/spacetelescope/poppy/blob/stable/notebooks/POPPY_tutorial.ipynb),

```python
import poppy

ap = poppy.MultiHexagonAperture(rings=3, flattoflat=2)           # 3 rings of 2 m segments yields 14.1 m circumscribed diameter
sec = poppy.SecondaryObscuration(secondary_radius=1.5, n_supports=4, support_width=0.1)   # secondary with spiders
atlast = poppy.CompoundAnalyticOptic( opticslist=[ap, sec], name='Mock ATLAST')           # combine into one optic
```

I get an error about an Astropy quantity being compared with a non-quantity object.

The error in POPPY occurs at the [`self.pupil_diam = max(self.pupil_diam, optic.pupil_diam)`](https://github.com/spacetelescope/poppy/blob/develop/poppy/optics.py#L2060) line in `CompoundAnalyticOptic`. In the example above, it seems to happen because `MultiHexagonAperture` has a float for `pupil_diam` while `SecondaryObscuration` has meters.

I'm not sure if the former should be in meters or if the latter should be a float, but from quickly checking other optical element classes it seems that the former should be a float, but is not because of the `.to_value()` call in this block: https://github.com/spacetelescope/poppy/blob/develop/poppy/optics.py#L1274-L1277

Thanks !

**Comment by mperrin** [comment]
Thanks very much for this error report, and the informative & useful debugging details in your note above. Much appreciated. I've fixed this in the PR #527. 

(And apologies it took so long to reply to this - as you may know, we were commissioning a segmented space telescope this spring ;-) and everything else not related to that was set aside while that was going on. Thanks for understanding!)
