### ISSUE TITLE
New python 3.10 error in zernike.py

### ISSUE THREAD

**Issue by maxwellmb** [spacetelescope/poppy#519]
In python 3.10 the math.factorial function throws an error when a float is input. 
For me this is now throwing an error at line 423 in zernike.py

My guess is that if you force the input to be an integer then it'll be happy.

**Comment by mperrin** [comment]
Hi Max, please check if you’re using the most recent poppy release (1.0.3). This issue was fixed a while ago in this PR: https://github.com/spacetelescope/poppy/pull/493 
So if you update to the most recent release you should have the fixed version. Cheers!

**Comment by maxwellmb** [comment]
d'oh! I was on 1.0.2. I upgraded and it works now.
