### ISSUE TITLE
Can poppy set the max and min value when using the wave.display?

### ISSUE THREAD

**Issue by qlmlp** [spacetelescope/poppy#534]
I would like to know if there is any source code for this wave [1].display.  Or is there any way I can change the colorbar value scale, like changing the left colorbar the same as the right?
waves[1].display(what='phase', colorbar=True,title = "Wavefront center")
<img width="602" alt="Screen Shot 2022-11-09 at 11 38 44 AM" src="https://user-images.githubusercontent.com/106215958/200888282-2bc91a4e-5411-4d35-9163-c92903a5c7fc.png">

**Comment by mperrin** [comment]
Hi, I think that function call lets you pass in `vmin=`, `vmax=` to change the scale values, yes. Try like
`waves[1].display(what='phase', colorbar=True,title = "Wavefront center", vmin=0.090, vmax=0.452)`

**Comment by mperrin** [comment]
Hi @qlmlp  - this is in response to an issue you filed about ~6 months ago. Did my reply then address your need? I assume so and will close this issue. Please feel free to reopen it if still relevant and still giving you some trouble.
